learning_users/basic_app/basic_app/urls.py
from django.conf.urls import url
from basic_app import views
from django.urls import path, re_path

# Template tagging :
app_name = 'basic_app'

urlpatterns = [
    re_path(r'^relative/$', views.relative, name = 'Joyan_Relative' ),
    re_path(r'^other/$', views.other, name = 'Joyan_Other' ),
]

learning_users/basic_app/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path , re_path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    re_path (r'^register/$', views.register, name = 'joy_register' ),
    re_path (r'^user_login/$', views.joe_user_login, name = 'joy_user_login' ),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path, re_path
from basic_app import views


urlpatterns = [
    re_path(r'^$',views.index, name = 'joyan_index' ),
    path('admin/', admin.site.urls),
    re_path(r'^basic_app/', include('basic_app.urls')),
    re_path(r'^logout/$', views.joe_user_logout, name = 'jpj_logout' ),
]

learning_users/basic_app/basic_app/models.py
from django.db import models

# Create your models here.

learning_users/basic_app/models.py
from django.db import models

# This is the user model class. It has user name and other properties of user.
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):
    # Note that User class already has all ifno needed for user. OneToOneField heps create a copy instea do inheriting it.
    # That is why the UserProfileInfo class didnt have User Class in its argument.
    user = models.OneToOneField (User,on_delete=models.CASCADE,)
    # Create Additional Fields
    joe_portfolio_site = models.URLField(blank=True)
    # For some reason not able to install Pillow. So, Leaving profile pic field.
    joy_profile_pic = models.ImageField ( upload_to = 'joyan_profile_pics', blank = True)

    # this is for sending user name if this class is called.
    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class JoyanUserForm (forms.ModelForm):
    password = forms.CharField (widget= forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email', 'password')

class JoeUserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        # For some reason not able to install Pillow. So, Leaving profile pic field.
        fields = ('joy_profile_pic','joe_portfolio_site')

        # fields = ('joe_portfolio_site', )

learning_users/basic_app/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    joyan_context_dict = {'Joyan_Text': 'Hello World' , 'Joyan_Number' : 101 }
    return render(request, 'basic_app/index.html', joyan_context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import JoyanUserForm, JoeUserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib. auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')
# This is a decorator for chekcin log in on
@login_required
def joe_user_logout (request):
    logout(request)
    # see in urls.py at project level that name given for the url for index is joyan_index
    return HttpResponseRedirect(reverse('joyan_index'))


def register(request):
    registered = False
    if request.method == 'POST':
        inst_of_user_form = JoyanUserForm(data=request.POST)
        inst_of_profile_form = JoeUserProfileInfoForm(data=request.POST)

        if inst_of_user_form.is_valid() and inst_of_profile_form.is_valid():
            user_joe = inst_of_user_form.save()
            user_joe.set_password (user_joe.password)
            user_joe.save()

            profile_jj = inst_of_profile_form.save(commit = False)
            profile_jj.user = user_joe
            # Commented as Pilllow is not geing isntalled.
            if 'joy_profile_pic' in request.FILES:
                profile_jj.joyan_profile_pic= request.FILES['joy_profile_pic']

            profile_jj.save()
            registered= True
        else:
            print(inst_of_user_form.errors,inst_of_profile_form.errors )
    else:
        inst_of_user_form = JoyanUserForm()
        inst_of_profile_form = JoeUserProfileInfoForm()

    contex_dict_jpj = {'jpj_user_form' :  inst_of_user_form,
                       'jj_user_prof_form' : inst_of_profile_form,
                       'josh_registered' :registered
                      }
    return render(request,'basic_app/registration.html',contex_dict_jpj )

def joe_user_login(request):
    if (request.method == 'POST'):
        joe_username = request.POST.get('username')
        # see in the login.html that the name given for field password is "joe_password"
        joe_password = request.POST.get('joe_password')

        jpj_user =authenticate(username=joe_username, password = joe_password)

        if jpj_user:
            if jpj_user.is_active:
                login(request, jpj_user)
                # see in urls.py at project level that name given for the url for index is joyan_index
                return HttpResponseRedirect(reverse('joyan_index'))
            else:
                HttpResponse("Account not active")
        else:
            print ('Some one tried to login and failed.')
            print ("user name : {} and pasword : {}".format(joe_username, joe_password))
            return HttpResponse("Invalid Log in Details")
    else:
        return render (request, 'basic_app/login.html', {})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md  bg-light">

      <a href= "{% url 'joyan_index' %}" class="navbar-brand">
        Brand
      </a>

      <div class="container">
        <ul class="navbar-nav text-center ms-auto">
          <li><a class="navbar-brand" href="{% url 'joyan_index' %}">Joe_Brand</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:joy_register' %}">Register</a></li>

          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'jpj_logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'basic_app:joy_user_login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block%}
      {% endblock %}
    </div>

  </body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Djnag Level 5</h1>  
</div>

{%endblock%}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
  <form class="" action="{% url 'basic_app:joy_user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">User Name</label>
    <input type="text" name="username" placeholder="Ente User Name Here...">

    <label for="joe_password">Password</label>
    <input type="password" name="joe_password" >

    <input type="Submit" name="" value="Log in">

  </form>
</div>
{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load static %}
{% block body_block%}

  <div class="jumbotron">
    {% if josh_registered %}
      <h1>Thank you!</h1>
    {% else %}
        <h1>REgister Here</h1>
        <h3>Fill Out the form</h3>
        <form class="" action="" enctype="multipart/form-data" method="POST" >
        {% csrf_token %}
        {{ jpj_user_form.as_p }}
        {{ jj_user_prof_form.as_p }}
        <input type="Submit" name="" value="Register">

        </form>
    {% endif%}
  </div>

{% endblock %}